use memo_db;
CREATE TABLE `TBL_MEMO` (
`ID` int(9) auto_increment COMMENT 'ID',
`TITLE` VARCHAR(15) NOT NULL COMMENT 'タイトル',
`CONTENT` VARCHAR(400) NOT NULL COMMENT '内容',
`CREATE_DAY` int(8) NOT NULL COMMENT '作成日',
`CREATE_TIME` int(8) NOT NULL COMMENT '作成時間',
PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
