version: "3.0"

services:
  db:
    build: ./mariadb/
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=memo_db
      - MYSQL_USER=memo_user
      - MYSQL_PASSWORD=memo_pass_db
  api:
    container_name: "api"
    build: .
    restart: always
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./main.py:/app/main.py